# Generated by Django 4.1.7 on 2024-07-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('white_player_elo', models.IntegerField(default=None)),
                ('black_player_elo', models.IntegerField(default=None)),
                ('game_color_winner', models.TextField()),
                ('date_time_played', models.DateTimeField(auto_now_add=True)),
                ('black_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black', to=settings.AUTH_USER_MODEL)),
                ('game_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to=settings.AUTH_USER_MODEL)),
                ('white_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=25)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('date_time_played', models.DateTimeField(auto_now_add=True)),
                ('elo', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sub_message', models.TextField()),
                ('sub_message_link', models.TextField()),
                ('notification_type', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_id', models.IntegerField()),
                ('move', models.CharField(max_length=6)),
                ('piece', models.CharField(max_length=1)),
                ('fen_string', models.CharField(max_length=90)),
                ('date_time_move_played', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parker_chess_app.game')),
                ('mover', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='white_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'move_id')},
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('account_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to=settings.AUTH_USER_MODEL)),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('main_account', 'account_following')},
            },
        ),
    ]
